server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: volumate-backend
  datasource:
    url: jdbc:sqlite:volumate.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLiteDialect
  # Logging configuration
  logging:
    level:
      com.volumate: DEBUG
      org.springframework.web: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# External API configuration
external:
  openfoodfacts:
    base-url: https://world.openfoodfacts.org/api/v2
    timeout: 10000 # 10 seconds
    retry-attempts: 3

# Cache configuration
cache:
  product:
    ttl: 3600 # 1 hour in seconds
    max-size: 1000

# Security configuration
security:
  cors:
    allowed-origins: "*" # In production, specify your React Native app's domain
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*" 